// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906233211_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Domain.Entities.EventoWebhook", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<DateTimeOffset?>("DataProcessado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_processado");

                    b.Property<DateTimeOffset>("DataRecebido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_recebido");

                    b.Property<string>("IdContrato")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_contrato");

                    b.Property<string>("IdTransacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_transacao");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StatusOrigem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status_origem");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status_pagamento");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("ultimo_erro");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_eventos_webhook");

                    b.HasIndex("IdContrato")
                        .HasDatabaseName("ix_eventos_webhook_id_contrato");

                    b.HasIndex("IdTransacao")
                        .IsUnique()
                        .HasDatabaseName("ux_eventos_webhook_id_transacao");

                    b.HasIndex("Status", "DataRecebido")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_eventos_webhook_status_data_recebido");

                    b.ToTable("eventos_webhook", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.StatusContrato", b =>
                {
                    b.Property<string>("IdContrato")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_contrato");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status_pagamento");

                    b.Property<DateTimeOffset>("UltimaDataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_data_pagamento");

                    b.Property<DateTimeOffset>("UltimaRecepcaoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_recepcao_em");

                    b.Property<Guid>("UltimoEventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ultimo_evento_id");

                    b.Property<decimal>("UltimoValor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ultimo_valor");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("IdContrato")
                        .HasName("pk_status_contrato");

                    b.HasIndex("UltimoEventoId")
                        .HasDatabaseName("ix_status_contrato_ultimo_evento_id");

                    b.ToTable("status_contrato", (string)null);
                });

            modelBuilder.Entity("Application.Domain.Entities.StatusContrato", b =>
                {
                    b.HasOne("Application.Domain.Entities.EventoWebhook", null)
                        .WithMany()
                        .HasForeignKey("UltimoEventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_status_contrato_eventos_webhook_ultimo_evento_id");
                });
#pragma warning restore 612, 618
        }
    }
}
